version: '3.8'

services:
  nginx:
    ports:
      - "80:80"
    build:
      dockerfile: ./docker/nginx/Dockerfile
    container_name: 'node_messenger_nginx'
    depends_on:
      - backend
    restart: always

  backend:
    #ports:
    #  - "3000:80"
    build:
      dockerfile: ./docker/node/Dockerfile
    container_name: 'node_messenger_backend'
    volumes:
      - ./app:/app
    restart: always
