version: '3.3'

services:
  backend:
    build:
      context: "./"
      dockerfile: "./docker/node/Dockerfile"
    container_name: 'node_messenger_backend'
    #volumes:
    #  - ./app:/app
    restart: unless-stopped

  frontend:
    ports:
      - "80:80"
    build:
      context: "./docker/nginx"
      dockerfile: "./Dockerfile"
    container_name: 'node_messenger_nginx'
    depends_on:
      - backend
    restart: unless-stopped